version: "2.9"
services:

  db:
    image: postgres
    container_name: MyContainer
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myDB
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./imports/db/:/docker-entrypoint-initdb.d/
    restart: always